services:

  wyoming-tts:
    image: mkbyme/wyoming-vietnamese-asr:1.0.10
    container_name: wyoming-tts
    user: "root"
    ports:
      - "10400:10400"
    environment:
      MODE: "wyoming"           # ← default, có thể bỏ
      HF_MODEL_ID: "hynt/Zipformer-30M-RNNT-6000h"
      HF_TOKEN: ""
      FORCE_DOWNLOAD: "false"
      USE_INT8: "false"
      TOKENS_FILE: "config.json"
      NUM_THREADS: "4"
      PROVIDER: "cpu"
      LOG_LEVEL: "INFO"
    volumes:
      - ./model/zipformer:/app/model
      - ./config.yaml:/app/config/config.yaml
    restart: unless-stopped

  wyoming-fastapi:
    image: mkbyme/wyoming-vietnamese-asr:1.0.10
    container_name: wyoming-fastapi
    user: "root"
    ports:
      - "8090:8090"
    environment:
      # ← switch sang FastAPI
      MODE: "fastapi"
      # chỉ định lại model id trong env (vì env -> ghi đè config.yaml)
      # HF_MODEL_ID: "NghiMe/NghiASR"
      # HF_TOKEN: ""
      # FORCE_DOWNLOAD: "false"
      # USE_INT8: "false"
      # NUM_THREADS: "4"
      # PROVIDER: "cpu"
      # API_HOST: "0.0.0.0"
      # API_PORT: "8090"
      # LOG_LEVEL: "INFO"
      # ENCODER_FILE: "encoder-epoch-4-avg-4.onnx"
      # DECODER_FILE: "decoder-epoch-4-avg-4.onnx"
      # JOINER_FILE: "joiner-epoch-4-avg-4.onnx"
      # TOKENS_FILE: "tokens.txt"

    volumes:
      - ./model/nghime:/app/model
      - ./config_nghimestudio.yaml:/app/config/config.yaml
    restart: unless-stopped
